In [1]:
import pandas as pd
data = pd.read_json('../data/output-analisys.json')

In [2]:
data.head()

       job_id                                             skills
0  4419256409  {'position': 'Analista de Dados', 'level': 'mi...
1  4409624796  {'position': 'Analista de Dados Júnior', 'leve...
2  4418846380  {'position': 'Data Engineer', 'level': 'assist...
3  4417995050  {'position': 'Analista de Dados de Sinistro', ...
4  4423299033  {'position': 'Analista de Dados Júnior', 'leve...

In [3]:
def check_skills(skills):
    if skills is None:
        return False
    if "technical_skills" not in skills or "soft_skills" not in skills:
        return False
    return True

rows = []

for _, row in data.iterrows():
    if not check_skills(row["skills"]):
        continue
    for skill in row["skills"]["technical_skills"]:
        rows.append({
            "job_id": row["job_id"],
            "skill": skill,
            "type_skill": "technical_skill",
            "level": row["skills"]["level"],
            "position": row["skills"]["position"]
        })

    for skill in row["skills"]["soft_skills"]:
        rows.append({
            "job_id": row["job_id"],
            "skill": skill,
            "type_skill": "soft_skill",
            "level": row["skills"]["level"],
            "position": row["skills"]["position"]
        })

skills_df = pd.DataFrame(rows)

In [4]:
skills_df[skills_df["type_skill"] != "technical_skill"]
skills_df.head()

       job_id       skill       type_skill level           position
0  4419256409      Python  technical_skill   mid  Analista de Dados
1  4419256409     PySpark  technical_skill   mid  Analista de Dados
2  4419256409   Spark SQL  technical_skill   mid  Analista de Dados
3  4419256409  Databricks  technical_skill   mid  Analista de Dados
4  4419256409  Delta Lake  technical_skill   mid  Analista de Dados

In [5]:
skills_df["position"].unique()

array(['Analista de Dados', 'Analista de Dados Júnior', 'Data Engineer',
       'Analista de Dados de Sinistro', 'Analista de Operações',
       'Estagiário de Dados', 'Data Science Intern',
       'Analista de Dados Pleno', 'Analista de Dados e Documentos',
       'Analytics Engineer', 'Engenheiro de Dados',
       'Senior Data Engineer', 'Analista de Dados Junior',
       'Data Engineer Junior', 'Analista de Dados de Suprimentos',
       'Junior Data Analyst', 'Analista de Indicadores',
       'Estagiário Dados', 'Analista de Inteligência Comercial e Mercado',
       'Analista de Dados ESG Pleno',
       'Estagiário Dados Inteligência Artificial',
       'Assistente de Inteligência de Mercado',
       'Analista de Dados Inteligência Operacional Júnior',
       'Analista de Dados Analytics Pleno',
       'Analista de Inteligência de Dados', 'Data Analyst Intern',
       'Junior Data Engineer', 'Engenheiro de Dados Pleno',
       'Data Analyst', 'Data Analytics', 'Analista Pleno de Dados',
       'Analista Business Intelligence Júnior',
       'Analista de Suporte de Banco de Dados',
       'Analista de Documentação Analítica',
       'Estagiário de Dados e Indicadores', 'Data Scientist',
       'Analista Dev Banco Dados',
       'Analista de Dados - Inteligência Comercial',
       'Analista de Dados Operações Júnior', 'Estágio em Dados',
       'Engenheiro de Dados Júnior', 'Finance Data Analyst',
       'Analista de Planejamento de Dados',
       'Estagiário Planejamento Dados', 'Engenheiro de Banco de Dados',
       'Engenheiro de Dados Databricks', 'Data Quality Engineer',
       'Data Engineer Pleno', 'Especialista Engenharia de Dados',
       'Data Analytics Engineer', 'Data Platform Engineer',
       'DataOps Engineer', 'Analista Automação Analytics Júnior',
       'Analista de Engenharia', 'Data Product Owner',
       'Assistente Qualidade', 'Staff Data Engineer',
       'Especialista em Engenharia de Dados', 'Data Engineer Specialist',
       'Estagiário Automações Análise de Dados',
       'Analista de Monitoramento e Prevenção de Perdas',
       'Analista Logístico de Dados', 'Analista de Sustentação',
       'Data Intern', 'Stagiaire Análise de Dados',
       'Analista Dados Junior', 'Assistente Power',
       'Analista de Dados Clínicos', 'Analista de Dados Projetos',
       'Analista de Processos', 'Engenheiro de Dados Power',
       'Analista de Dados Insights', 'ETL Data Engineer',
       'Analista Inteligência Dados Júnior',
       'Analista de Inteligência de Dados Pleno',
       'Engenheiro de Dados Junior',
       'Especialista em Indicadores Industriais',
       'Analista Resultados Junior', 'Engenheiro Trainee',
       'Analista Engenheiro Dados Suprimentos',
       'Analista Planejamento Dados Junior',
       'Intern - Business Intelligence', 'Estágio Envasamento Dados',
       'Estágio em Public Affairs', 'Business Development Intern',
       'Data Solutions Engineer', 'Staff Analytics Engineer',
       'Senior Data Platform Engineer',
       'Engenheiro de Dados - Analítica Avançada',
       'Engenheiro de Dados Azure', 'Estagiário Análise de Dados',
       'Analista Melhoria Contínua', 'Analista de Dados Infraestrutura',
       'Analista Processos Controles Júnior',
       'Business Intelligence Intern', 'Estagiário Dados Processos',
       'Artificial Intelligence Engineer', 'Analista Planejamento',
       'Data Engineer Consultant', 'Analista Logística',
       'Analista Pleno Data Analytics', 'Data Performance Intern',
       'Analista de Dados Contratos',
       'Assistente Pleno Inteligência de Negócios',
       'Analytics Engineer III', 'Analista Sênior - Engenheiro de Dados',
       'Data Analyst - Intern', 'Analista de Operações de Dados Júnior',
       'Assistente Inteligência Mercado', 'Analista de Dados Sênior',
       'Estagiário Dados Labs', 'Analista Junior Pleno',
       'Fraud Data Analyst', 'Analista de Indicadores de Processos',
       'Analista de Projetos de Dados', 'Analista Sustentabilidade',
       'Data Visualization Lab Intern', 'Analista de Sistema de Gestão',
       'Data Engineer III', 'Analista Inteligência Operacional III',
       'Analista Sênior de Dados', 'Assistente de Suporte',
       'Analista Pleno de Dados - Prevenção de Fraude em Pagamentos',
       'Data Analyst - Legal Litigation Efficiency',
       'Especialista Inteligência de Dados',
       'Analista de Desenvolvimento de Negócios - Foco em Dados',
       'Analista de Processos e Indicadores', 'Senior Analytics Engineer',
       'Analista Administrativo Relações Institucionais',
       'Senior Data Processing Engineer', 'Especialista Dados',
       'Cloud Data Architect / Data Engineer',
       'Cloud Data Architect Data Engineer AWS',
       'Analista de Dados Industriais Pleno', 'Analista Júnior Empiricus',
       'Engenheiro Inteligência Artificial - Diretor',
       'Analista de Dados Gerenciais Júnior',
       'Analista de Validação de Dados', 'Analista Data Science Dados',
       'Analista de Atraativos de Desempenho',
       'Analista de Tecnologia da Informação', 'Staff Data Scientist',
       'Engenheiro Soluções Dados Azure', 'Especialista em Dados',
       'Senior Lead Data Engineer', 'Data Science Engineer',
       'Gerente de Dados', 'Lead Dados', 'Analista de Processos Ágeis',
       'Analista Controladoria', 'Analista Projetos Engenharia',
       'Especialista Inteligência Competitiva',
       'Estagiário em Processamento de Dados',
       'Analista Pleno Serviços Externos Corporativo',
       'Analista de Dados Operações Jurídicas', 'Industrial Data Analyst',
       'Analista de Dados Operações',
       'Analista de Estratégia de Prevenção de Fraude',
       'Senior Data Analyst', 'Analista Planejamento Dados',
       'Analista de Dados Híbrido', 'Analista de Qualidade de Processos',
       'Analista Administrativo Pleno', 'Analista Backoffice Performance',
       'Analista de Dados Sistemas',
       'CAS Analista de Dados - Auditoria Interna',
       'Analista de Sistemas', 'Especialista Produto Databricks',
       'Finance Data Specialist', 'Analista Pleno',
       'Senior Machine Learning Engineer',
       'Database Reliability Engineer', 'Developer',
       'Engenheiro de Sistemas', 'Tech Lead - Dados Analytics',
       'Analista de Dados SIOP', 'Analista de Gestão', 'Technology',
       'Estagiário Comercial', 'Data Science Specialist',
       'Trainee Central Intelligence',
       'Analista de Indicadores Industriais',
       'Analista de Dados de Negócio Farmacêutico',
       'Analista de Base de Dados Híbrido', 'Engenheiro de Dados III',
       'Analista Sistemas Júnior', 'Estagiário',
       'Mestre Tecnologia Dados Inovação', 'Banco Talentos Tech',
       'Analista de Indicadores de Processos - People Analytics',
       'Analista Controle Gestão', 'Estagiária de Dados',
       'Data Analyst Engineer', 'Analista Desenvolvimento',
       'Estagiário Ciência Dados',
       'Analista de Modelagem de Data Warehouse',
       'Analytics Engineer Junior', 'Operations Intern',
       'Machine Learning Engineer',
       'Analista de Dados Pós-Vendas Veículos Pesados',
       'Data Science Business Development Specialist', 'Datahub Analyst',
       'MLOps Engineer', 'Analista Desenvolvimento ETL',
       'Senior Data Operations Analyst', 'Consultor',
       'Analista Júnior Migração de Dados', 'Analista Cadastro',
       'Analista', 'Analista Planejamento Inteligência Dados Júnior',
       'Coordenador de Dados de Mercado',
       'Especialista em Dados - Auditoria Interna',
       'Senior Associate - Data Insights Tech',
       'Analista de Dados de Compras', 'Estagiário Dados Gestão Pessoas',
       'Intern', 'Analista Sede Administrativa',
       'Analista de Desenvolvimento',
       'Engenheiro de Confiabilidade de Banco de Dados',
       'Analista de Processos de Automação', 'Analista de Dados DBA',
       'Analista Administrativo Multas',
       'Analista de Dados Inteligência Comercial Pleno',
       'Data Visualization Specialist', 'Analista Operações Júnior',
       'Data Analysis Intern', 'Analista Compras Planejamento',
       'Staff Engineer', 'Engenheiro Florestal', 'Analista de Preço',
       'Auditor Interno', 'Analista Junior',
       'Engenheiro de Infraestrutura de Arquitetura',
       'Desenvolvedor Automacoes', 'Software Engineer Specialist',
       'Engenheiro de Tecnologia da Informação', 'Software Developer',
       'Data Scientist Specialist', 'Especialista Desenvolvedor',
       'Business Intelligence Analyst', 'Data Product Manager',
       'Resources Human', 'Senior Developer',
       'Analista Desenvolvimento Analítico Pleno',
       'Analista de Monitoria de Qualidade', 'Analista de Dados Varejo',
       'Data Scientist III', 'Engenheiro de Materiais',
       'Analista Programador SQL', 'SQL Developer', 'Engineering Manager',
       'Data Architect', 'Analista de Dados Automação',
       'Forward Deployed Data Scientist', 'Engineering',
       'Data Analytics Specialist',
       'Analista de Tecnologia da Informação - Especialista em Aprendizado de Máquina',
       'Analista RGN', 'Analista Dados Sênior',
       'Líder de Integrações de Sistemas de Dados',
       'Python Engineer - Machine Learning Focus',
       'Especialista Soluções Dados',
       'Coordenador de Desempenho Operacional',
       'Consultor Dados Business Intelligence',
       'Specialista em Analytics de Cibersegurança',
       'Analista Inteligencia Comercial Pleno', 'Senior Database Analyst',
       'Senior Database Reliability Engineer',
       'Senior Client Integration Engineer', 'Research Engineer',
       'Especialista em Ciência de Dados',
       'Staff Data Scientist Engineer', 'Technical Support Engineer',
       'Analista de Governança de Dados Pleno', 'Martech Analyst',
       'Big Data Engineer', 'Senior Backend Engineer',
       'Analista Inovação Aberta Dados Sênior', 'Data Engineer Intern',
       'Analista Contas Pagar Pleno',
       'Engenheiro de Dados Azure Databricks',
       'Analista de Dados Empresarial',
       'Analista de Processos de Cadastro', 'Engenheira Sistemas Pleno',
       'Senior Software Engineer - Data Acquisition',
       'Inteligência Artificial Especialista',
       'Especialista em Governança de Dados e Inteligência Artificial',
       'Especialista Dados Supply Chain', 'Forward Deployed Engineer',
       'Analista Engenharia de Dados Pleno',
       'Commercial Excellence Data Analytics Specialist',
       'Analista Tecnologia Dados Pleno', 'Analista Reporting',
       'Analista de Gestão de Estoques', 'Data Importation Analyst',
       'Analista de Planejamento de Dados Produto Pleno',
       'Analista de Modelagem de Dados', 'DATA SCIENTIST',
       'RESULTS ANALYST', 'DATA ANALYST', 'COLLECTIONS ANALYST',
       'INTELLIGENCE ASSISTANT', 'DATA SCIENCE INTERN', 'DATA ENGINEER',
       'DATA ANALYTICS COORDINATOR', 'HR DATA ANALYST',
       'OPERATIONAL REQUIREMENTS ANALYST', 'ETL DATA ANALYST',
       'PROCESS SPECIALIST', 'OPERATIONAL INTELLIGENCE ANALYST',
       'COMMERCIAL DATA GOVERNANCE ANALYST',
       'SENIOR BACKEND DATA ENGINEER', 'BUSINESS INTELLIGENCE SPECIALIST',
       'DATA SIMULATION INTERN', 'DATA MIGRATION ANALYST',
       'DATA ENGINEER TRAINEE', 'SENIOR DATA ENGINEER',
       'MARKET INTELLIGENCE ANALYST', 'PROCESS ANALYST',
       'QUALITY ANALYST - CUSTOMER EXCELLENCE', 'BUSINESS DATA ANALYST',
       'Quality Analyst', 'DATA MANAGEMENT ENGINEER',
       'SENIOR DATA PLATFORM ENGINEER', 'OPERATIONS EFFICIENCY ANALYST',
       'SENIOR TALENT ANALYST', 'SOFTWARE ENGINEER', 'APPLIED ANALYST',
       'BUSINESS INTELLIGENCE ANALYST',
       'ARTIFICIAL INTELLIGENCE SPECIALIST', 'MACHINE LEARNING ENGINEER',
       'DATA AUTOMATION ANALYST', 'SYSTEMS ANALYST',
       'INFORMATION SECURITY ANALYST', 'DATA DEVELOPMENT ANALYST',
       'BUSINESS INTELLIGENCE INTERN', 'MLOPS ENGINEER',
       'BUSINESS SYSTEMS ANALYST', 'DATA ENGINEERING SPECIALIST',
       'DATA SOLUTIONS ENGINEER', 'DATA PRODUCTS SPECIALIST',
       'GENAI ENGINEER', 'OPERATIONS PERFORMANCE ANALYST',
       'Prompt Analyst', 'Power Platform Analyst', 'DATA ANALYST INTERN',
       'PROJECT ENGINEER', 'Data Technology Maintenance Supervisor',
       'DATA INTELLIGENCE INTERN', 'Regulation Analyst',
       'Generative AI Engineer', 'Logistics Planning Analyst',
       'Monitoring Analyst', 'Data Intelligence Analyst',
       'OPERATIONS SPECIALIST', 'STAFF DATA SCIENTIST',
       'Performance Planning Analyst', 'DATA ENGINEER SPECIALIST',
       'STATISTICAL ANALYST', 'Data Science Coordinator',
       'Backend Software Engineer', 'Product Assistant',
       'ANALYTICS INTERN', 'Salesforce Cloud Engineer',
       'Operations Coordinator', 'DATA ANALYTICS INTERN',
       'DATA PLATFORM ENGINEER', 'Data Engineering Lead', 'ETL ENGINEER',
       'Snowflake Engineer'], dtype=object)

In [6]:
import unidecode

skills_df["position_normalized"] = (
    skills_df["position"]
    .str.lower()
    .apply(unidecode.unidecode)
    .str.strip()
)

In [7]:
skills_df["position_normalized"].unique()

array(['analista de dados', 'analista de dados junior', 'data engineer',
       'analista de dados de sinistro', 'analista de operacoes',
       'estagiario de dados', 'data science intern',
       'analista de dados pleno', 'analista de dados e documentos',
       'analytics engineer', 'engenheiro de dados',
       'senior data engineer', 'data engineer junior',
       'analista de dados de suprimentos', 'junior data analyst',
       'analista de indicadores', 'estagiario dados',
       'analista de inteligencia comercial e mercado',
       'analista de dados esg pleno',
       'estagiario dados inteligencia artificial',
       'assistente de inteligencia de mercado',
       'analista de dados inteligencia operacional junior',
       'analista de dados analytics pleno',
       'analista de inteligencia de dados', 'data analyst intern',
       'junior data engineer', 'engenheiro de dados pleno',
       'data analyst', 'data analytics', 'analista pleno de dados',
       'analista business intelligence junior',
       'analista de suporte de banco de dados',
       'analista de documentacao analitica',
       'estagiario de dados e indicadores', 'data scientist',
       'analista dev banco dados',
       'analista de dados - inteligencia comercial',
       'analista de dados operacoes junior', 'estagio em dados',
       'engenheiro de dados junior', 'finance data analyst',
       'analista de planejamento de dados',
       'estagiario planejamento dados', 'engenheiro de banco de dados',
       'engenheiro de dados databricks', 'data quality engineer',
       'data engineer pleno', 'especialista engenharia de dados',
       'data analytics engineer', 'data platform engineer',
       'dataops engineer', 'analista automacao analytics junior',
       'analista de engenharia', 'data product owner',
       'assistente qualidade', 'staff data engineer',
       'especialista em engenharia de dados', 'data engineer specialist',
       'estagiario automacoes analise de dados',
       'analista de monitoramento e prevencao de perdas',
       'analista logistico de dados', 'analista de sustentacao',
       'data intern', 'stagiaire analise de dados',
       'analista dados junior', 'assistente power',
       'analista de dados clinicos', 'analista de dados projetos',
       'analista de processos', 'engenheiro de dados power',
       'analista de dados insights', 'etl data engineer',
       'analista inteligencia dados junior',
       'analista de inteligencia de dados pleno',
       'especialista em indicadores industriais',
       'analista resultados junior', 'engenheiro trainee',
       'analista engenheiro dados suprimentos',
       'analista planejamento dados junior',
       'intern - business intelligence', 'estagio envasamento dados',
       'estagio em public affairs', 'business development intern',
       'data solutions engineer', 'staff analytics engineer',
       'senior data platform engineer',
       'engenheiro de dados - analitica avancada',
       'engenheiro de dados azure', 'estagiario analise de dados',
       'analista melhoria continua', 'analista de dados infraestrutura',
       'analista processos controles junior',
       'business intelligence intern', 'estagiario dados processos',
       'artificial intelligence engineer', 'analista planejamento',
       'data engineer consultant', 'analista logistica',
       'analista pleno data analytics', 'data performance intern',
       'analista de dados contratos',
       'assistente pleno inteligencia de negocios',
       'analytics engineer iii', 'analista senior - engenheiro de dados',
       'data analyst - intern', 'analista de operacoes de dados junior',
       'assistente inteligencia mercado', 'analista de dados senior',
       'estagiario dados labs', 'analista junior pleno',
       'fraud data analyst', 'analista de indicadores de processos',
       'analista de projetos de dados', 'analista sustentabilidade',
       'data visualization lab intern', 'analista de sistema de gestao',
       'data engineer iii', 'analista inteligencia operacional iii',
       'analista senior de dados', 'assistente de suporte',
       'analista pleno de dados - prevencao de fraude em pagamentos',
       'data analyst - legal litigation efficiency',
       'especialista inteligencia de dados',
       'analista de desenvolvimento de negocios - foco em dados',
       'analista de processos e indicadores', 'senior analytics engineer',
       'analista administrativo relacoes institucionais',
       'senior data processing engineer', 'especialista dados',
       'cloud data architect / data engineer',
       'cloud data architect data engineer aws',
       'analista de dados industriais pleno', 'analista junior empiricus',
       'engenheiro inteligencia artificial - diretor',
       'analista de dados gerenciais junior',
       'analista de validacao de dados', 'analista data science dados',
       'analista de atraativos de desempenho',
       'analista de tecnologia da informacao', 'staff data scientist',
       'engenheiro solucoes dados azure', 'especialista em dados',
       'senior lead data engineer', 'data science engineer',
       'gerente de dados', 'lead dados', 'analista de processos ageis',
       'analista controladoria', 'analista projetos engenharia',
       'especialista inteligencia competitiva',
       'estagiario em processamento de dados',
       'analista pleno servicos externos corporativo',
       'analista de dados operacoes juridicas', 'industrial data analyst',
       'analista de dados operacoes',
       'analista de estrategia de prevencao de fraude',
       'senior data analyst', 'analista planejamento dados',
       'analista de dados hibrido', 'analista de qualidade de processos',
       'analista administrativo pleno', 'analista backoffice performance',
       'analista de dados sistemas',
       'cas analista de dados - auditoria interna',
       'analista de sistemas', 'especialista produto databricks',
       'finance data specialist', 'analista pleno',
       'senior machine learning engineer',
       'database reliability engineer', 'developer',
       'engenheiro de sistemas', 'tech lead - dados analytics',
       'analista de dados siop', 'analista de gestao', 'technology',
       'estagiario comercial', 'data science specialist',
       'trainee central intelligence',
       'analista de indicadores industriais',
       'analista de dados de negocio farmaceutico',
       'analista de base de dados hibrido', 'engenheiro de dados iii',
       'analista sistemas junior', 'estagiario',
       'mestre tecnologia dados inovacao', 'banco talentos tech',
       'analista de indicadores de processos - people analytics',
       'analista controle gestao', 'estagiaria de dados',
       'data analyst engineer', 'analista desenvolvimento',
       'estagiario ciencia dados',
       'analista de modelagem de data warehouse',
       'analytics engineer junior', 'operations intern',
       'machine learning engineer',
       'analista de dados pos-vendas veiculos pesados',
       'data science business development specialist', 'datahub analyst',
       'mlops engineer', 'analista desenvolvimento etl',
       'senior data operations analyst', 'consultor',
       'analista junior migracao de dados', 'analista cadastro',
       'analista', 'analista planejamento inteligencia dados junior',
       'coordenador de dados de mercado',
       'especialista em dados - auditoria interna',
       'senior associate - data insights tech',
       'analista de dados de compras', 'estagiario dados gestao pessoas',
       'intern', 'analista sede administrativa',
       'analista de desenvolvimento',
       'engenheiro de confiabilidade de banco de dados',
       'analista de processos de automacao', 'analista de dados dba',
       'analista administrativo multas',
       'analista de dados inteligencia comercial pleno',
       'data visualization specialist', 'analista operacoes junior',
       'data analysis intern', 'analista compras planejamento',
       'staff engineer', 'engenheiro florestal', 'analista de preco',
       'auditor interno', 'analista junior',
       'engenheiro de infraestrutura de arquitetura',
       'desenvolvedor automacoes', 'software engineer specialist',
       'engenheiro de tecnologia da informacao', 'software developer',
       'data scientist specialist', 'especialista desenvolvedor',
       'business intelligence analyst', 'data product manager',
       'resources human', 'senior developer',
       'analista desenvolvimento analitico pleno',
       'analista de monitoria de qualidade', 'analista de dados varejo',
       'data scientist iii', 'engenheiro de materiais',
       'analista programador sql', 'sql developer', 'engineering manager',
       'data architect', 'analista de dados automacao',
       'forward deployed data scientist', 'engineering',
       'data analytics specialist',
       'analista de tecnologia da informacao - especialista em aprendizado de maquina',
       'analista rgn', 'analista dados senior',
       'lider de integracoes de sistemas de dados',
       'python engineer - machine learning focus',
       'especialista solucoes dados',
       'coordenador de desempenho operacional',
       'consultor dados business intelligence',
       'specialista em analytics de ciberseguranca',
       'analista inteligencia comercial pleno', 'senior database analyst',
       'senior database reliability engineer',
       'senior client integration engineer', 'research engineer',
       'especialista em ciencia de dados',
       'staff data scientist engineer', 'technical support engineer',
       'analista de governanca de dados pleno', 'martech analyst',
       'big data engineer', 'senior backend engineer',
       'analista inovacao aberta dados senior', 'data engineer intern',
       'analista contas pagar pleno',
       'engenheiro de dados azure databricks',
       'analista de dados empresarial',
       'analista de processos de cadastro', 'engenheira sistemas pleno',
       'senior software engineer - data acquisition',
       'inteligencia artificial especialista',
       'especialista em governanca de dados e inteligencia artificial',
       'especialista dados supply chain', 'forward deployed engineer',
       'analista engenharia de dados pleno',
       'commercial excellence data analytics specialist',
       'analista tecnologia dados pleno', 'analista reporting',
       'analista de gestao de estoques', 'data importation analyst',
       'analista de planejamento de dados produto pleno',
       'analista de modelagem de dados', 'results analyst',
       'collections analyst', 'intelligence assistant',
       'data analytics coordinator', 'hr data analyst',
       'operational requirements analyst', 'etl data analyst',
       'process specialist', 'operational intelligence analyst',
       'commercial data governance analyst',
       'senior backend data engineer', 'business intelligence specialist',
       'data simulation intern', 'data migration analyst',
       'data engineer trainee', 'market intelligence analyst',
       'process analyst', 'quality analyst - customer excellence',
       'business data analyst', 'quality analyst',
       'data management engineer', 'operations efficiency analyst',
       'senior talent analyst', 'software engineer', 'applied analyst',
       'artificial intelligence specialist', 'data automation analyst',
       'systems analyst', 'information security analyst',
       'data development analyst', 'business systems analyst',
       'data engineering specialist', 'data products specialist',
       'genai engineer', 'operations performance analyst',
       'prompt analyst', 'power platform analyst', 'project engineer',
       'data technology maintenance supervisor',
       'data intelligence intern', 'regulation analyst',
       'generative ai engineer', 'logistics planning analyst',
       'monitoring analyst', 'data intelligence analyst',
       'operations specialist', 'performance planning analyst',
       'statistical analyst', 'data science coordinator',
       'backend software engineer', 'product assistant',
       'analytics intern', 'salesforce cloud engineer',
       'operations coordinator', 'data analytics intern',
       'data engineering lead', 'etl engineer', 'snowflake engineer'],
      dtype=object)

In [8]:
from unidecode import unidecode


def normalize_position(position):
    p = unidecode(str(position).lower().strip())

    # =========================
    # DATA LEADERSHIP
    # =========================
    if any(x in p for x in [
        "gerente de dados",
        "lead dados",
        "data lead",
        "head of data",
        "tech lead",
        "data engineering lead",
        "data analytics coordinator",
        "data science coordinator",
        "coordenador de dados",
        "coordenador de dados de mercado",
        "engineering manager"
    ]):
        return "Data Leadership"

    # =========================
    # DATA PRODUCT
    # =========================
    if any(x in p for x in [
        "data product owner",
        "data product manager",
        "data products specialist"
    ]):
        return "Data Product"

    # =========================
    # DATA ARCHITECT
    # =========================
    if any(x in p for x in [
        "data architect",
        "cloud data architect"
    ]):
        return "Data Architect"

    # =========================
    # DATA GOVERNANCE
    # =========================
    if any(x in p for x in [
        "governanca de dados",
        "data governance",
        "commercial data governance analyst"
    ]):
        return "Data Governance"

    # =========================
    # DATA SCIENTIST
    # =========================
    if any(x in p for x in [
        "data scientist",
        "staff data scientist",
        "data science",
        "machine learning",
        "mlops",
        "artificial intelligence",
        "inteligencia artificial",
        "genai",
        "generative ai",
        "ai engineer",
        "especialista em ciencia de dados",
        "forward deployed data scientist",
        "python engineer - machine learning focus",
        "analista data science dados"
    ]):
        return "Data Scientist"

    # =========================
    # ANALYTICS ENGINEER
    # =========================
    if any(x in p for x in [
        "analytics engineer",
        "analytics engineer iii",
        "analytics engineer junior",
        "staff analytics engineer",
        "senior analytics engineer",
        "data analytics engineer",
        "data analyst engineer"
    ]):
        return "Analytics Engineer"

    # =========================
    # DATA ENGINEER
    # =========================
    if any(x in p for x in [
        "data engineer",
        "senior data engineer",
        "junior data engineer",
        "staff data engineer",
        "data engineer specialist",
        "data engineer consultant",
        "data engineer trainee",
        "engenheiro de dados",
        "engenheiro de banco de dados",
        "engenheiro de dados azure",
        "engenheiro de dados azure databricks",
        "engenheiro solucoes dados",
        "engenheiro de confiabilidade de banco de dados",
        "etl engineer",
        "etl data engineer",
        "snowflake engineer",
        "data platform engineer",
        "senior data platform engineer",
        "dataops engineer",
        "database reliability engineer",
        "senior database reliability engineer",
        "big data engineer",
        "data quality engineer",
        "data solutions engineer",
        "data management engineer",
        "data engineering specialist",
        "especialista engenharia de dados",
        "especialista em engenharia de dados",
        "suporte de banco de dados",
        "dev banco dados",
        "databricks"
    ]):
        return "Data Engineer"

    # =========================
    # BI / ANALYTICS
    # =========================
    if any(x in p for x in [
        "business intelligence",
        "business intelligence analyst",
        "business intelligence specialist",
        "inteligencia comercial",
        "inteligencia de mercado",
        "inteligencia de negocios",
        "inteligencia competitiva",
        "people analytics",
        "data analytics",
        "data visualization",
        "data visualization specialist",
        "consultor dados business intelligence",
        "martech analyst",
        "analytics intern",
        "specialista em analytics",
        "indicadores"
    ]):
        return "BI Analyst"

    # =========================
    # DATA ANALYST
    # =========================
    if any(x in p for x in [
        "analista de dados",
        "analista dados",
        "data analyst",
        "finance data analyst",
        "fraud data analyst",
        "industrial data analyst",
        "business data analyst",
        "hr data analyst",
        "etl data analyst",
        "datahub analyst",
        "data migration analyst",
        "data automation analyst",
        "data development analyst",
        "data intelligence analyst",
        "market intelligence analyst",
        "senior data analyst",
        "dados junior",
        "dados pleno",
        "dados senior",
        "planejamento dados",
        "operacoes de dados",
        "projetos de dados",
        "validacao de dados",
        "inteligencia de dados",
        "especialista dados",
        "especialista em dados",
        "finance data specialist",
        "analista de modelagem de dados",
        "analista de base de dados",
        "analista de governanca de dados",
        "analista de dados dba",
        "coordenador de dados de mercado"
    ]):
        return "Data Analyst"

    # =========================
    # INTERNS
    # =========================
    if any(x in p for x in [
        "intern",
        "estagi",
        "stagiaire",
        "trainee"
    ]):
        return "Data Intern"

    # =========================
    # NÃO É CARREIRA DE DADOS
    # =========================
    return None

In [9]:
skills_df["position_group"] = (
    skills_df["position_normalized"]
    .fillna("")
    .apply(normalize_position)
)

In [10]:
positions = (
    skills_df
    .groupby("position_group")["job_id"]
    .nunique()
    .reset_index(name="total")
    .sort_values("total", ascending=False)
)
positions

       position_group  total
4       Data Engineer    291
2        Data Analyst    257
9      Data Scientist     52
1          BI Analyst     37
6         Data Intern     33
0  Analytics Engineer     23
7     Data Leadership      9
3      Data Architect      4
5     Data Governance      3
8        Data Product      3

In [11]:
skills_df["level"].unique()

array(['mid', 'junior', 'assistant', 'entry', 'senior', 'null', 'pleno',
       'assistente', 'pleno|sênior', 'experiência não aplicável', None],
      dtype=object)

In [12]:
levels = (
  skills_df.
  groupby("level")["job_id"].
  nunique().
  reset_index(name="total").
  sort_values("total", ascending=False)
)
levels

                       level  total
9                     senior    343
5                        mid    271
2                      entry    108
6                       null     88
4                     junior     24
0                  assistant      5
1                 assistente      5
7                      pleno      3
3  experiência não aplicável      1
8               pleno|sênior      1

In [13]:
mapping = {
  "junior": "entry",
  "assistente": "assistant",
  "junior": "entry",
  "pleno": "mid"
}

skills_df["level_grouped"] = (
  skills_df["level"].replace(mapping)
)
levels = (
  skills_df.
  groupby("level_grouped")["job_id"].
  nunique().
  reset_index(name="total").
  sort_values("total", ascending=False)
)
levels

               level_grouped  total
6                     senior    343
3                        mid    274
1                      entry    132
4                       null     88
0                  assistant     10
2  experiência não aplicável      1
5               pleno|sênior      1

In [14]:
skills_df.head()

,job_id,skill,type_skill,level,position,position_normalized,position_group,level_grouped
0,4419256409,Python,technical_skill,mid,Analista de Dados,analista de dados,Data Analyst,mid
1,4419256409,PySpark,technical_skill,mid,Analista de Dados,analista de dados,Data Analyst,mid
2,4419256409,Spark SQL,technical_skill,mid,Analista de Dados,analista de dados,Data Analyst,mid
3,4419256409,Databricks,technical_skill,mid,Analista de Dados,analista de dados,Data Analyst,mid
4,4419256409,Delta Lake,technical_skill,mid,Analista de Dados,analista de dados,Data Analyst,mid

In [15]:
skills = (
    skills_df
    .groupby("skill")["job_id"]
    .nunique()
    .reset_index(name="total")
    .sort_values("total", ascending=False)
)
skills

                             skill  total
2373                           SQL    600
2170                        Python    537
2069                      Power BI    270
573                  Communication    239
1006                           ETL    219
...                            ...    ...
351          Azure Virtual Network      1
352                            BDD      1
340                      Azure IAM      1
332   Azure Data Lake Storage Gen2      1
1345        Habilidades analíticas      1

[2849 rows x 2 columns]

In [16]:
import unidecode
skills_df["skill_normalized"] = (
    skills_df["skill"]
    .str.lower()
    .apply(unidecode.unidecode)
    .str.strip()
)

In [17]:
from unidecode import unidecode

def standardize_skill(skill):
    # Converte para string, remove acentos, joga para minúsculo e tira espaços extras
    s = unidecode(str(skill).lower().strip())

    # =========================================================
    # 1. MAPEAMENTO EXATO (Dicionário de Sinônimos/Erros comuns)
    # =========================================================
    # Tudo aqui deve estar em minúsculo e sem acento
    exact_matches = {
        "cosmosdb": "Azure Cosmos DB",
        "azure cosmos db": "Azure Cosmos DB",
        "cosmos db": "Azure Cosmos DB",
        
        "powerbi": "Power BI",
        "power bi": "Power BI",
        "microsoft power bi": "Power BI",
        
        "excel": "Microsoft Excel",
        "microsoft excel": "Microsoft Excel",
        "excel avancado": "Microsoft Excel",
        "excel intermediario": "Microsoft Excel",
        
        "aws": "AWS",
        "amazon web services": "AWS",
        "amazon web services (aws)": "AWS",
        
        "gcp": "Google Cloud Platform",
        "google cloud": "Google Cloud Platform",
        "google cloud platform (gcp)": "Google Cloud Platform",
        
        "postgres": "PostgreSQL",
        "postgresql": "PostgreSQL",
        
        "ms sql server": "SQL Server",
        "sql server": "SQL Server",
        "mssql": "SQL Server",
        "microsoft sql server": "SQL Server",
        
        "phyton": "Python", # Erro de digitação comum
        "python": "Python",
        
        "pyspark": "PySpark",
        "spark": "Apache Spark",
        "apache spark": "Apache Spark",
        
        "dbt (data build tool)": "dbt",
        "dbt core": "dbt",
        "dbt": "dbt",
        
        "llms": "LLM",
        "llm": "LLM",
        "large language models (llms)": "LLM",
        "large language models": "LLM"
    }

    # Se a string normalizada for uma chave exata, retorna o valor oficial
    if s in exact_matches:
        return exact_matches[s]

    # =========================================================
    # 2. MAPEAMENTO POR SUBSTRING (Pega variações maiores)
    # =========================================================
    # A ordem importa aqui. Coloque termos mais específicos primeiro.
    
    if "cosmos" in s:
        return "Azure Cosmos DB"
        
    if "databricks" in s:
        return "Databricks" # Vai capturar "Databricks Jobs", "Azure Databricks", etc.
        
    if "bigquery" in s or "big query" in s:
        return "Google BigQuery"
        
    if "machine learning" in s:
        return "Machine Learning"
        
    if "comunicacao" in s:
        return "Comunicação" # Unifica "boa comunicacao", "comunicacao verbal", etc.

    # =========================================================
    # 3. RETORNO PADRÃO
    # =========================================================
    # Se não cair em nenhuma regra de unificação, retorna a string original 
    # apenas formatada em Title Case (Primeiras Letras Maiúsculas) para ficar limpo.
    return str(skill).strip().title()

In [21]:
skills_df["skill_grouped"] = (
    skills_df["skill_normalized"]
    .fillna("")
    .apply(standardize_skill)
)
skills = (
    skills_df
    .groupby("skill_grouped")["job_id"]
    .nunique()
    .reset_index(name="total")
    .sort_values("total", ascending=False)
)
skills

              skill_grouped  total
2308                    Sql    600
1990                 Python    537
1893               Power BI    279
516           Communication    239
972                     Etl    222
...                     ...    ...
2559           Webscrapping      1
2560                Weibull      1
2561       Weights & Biases      1
2562      Whatsapp Business      1
2563  Whatsapp Business Api      1

[2591 rows x 2 columns]

In [ ]:
import json

skills = pd.DataFrame(
    skills_df["skill"].unique(),
    columns=["skill"]
)
with open("skills.json", "w", encoding="utf-8") as f:
    json.dump(
        skills.to_dict(orient="records"),
        f,
        ensure_ascii=False,
        indent=2
    )

In [24]:
skills_df.to_csv("../data/skills_standardized.csv", index=False)

In [26]:
skills = (
    skills_df
    .groupby("skill_grouped")["job_id"]
    .nunique()
    .reset_index(name="total")
    .sort_values("total", ascending=False)
)
with open("skills.json", "w", encoding="utf-8") as f:
    json.dump(
        skills.to_dict(orient="records"),
        f,
        ensure_ascii=False,
        indent=2
    )